exports.fixBug = async () => {
  const x = {
    accurate_grams: true,
    allow_public: null,
    average_frequency: 2,
    blatantly_unhealthy: false,
    breakfast: false,
    calories: 701.45988,
    can_be_bulk: true,
    carbs: 3.33608,
    category_id: 1,
    cholesterol: 344.54838,
    complexity: 5.5,
    cook_time: 45,
    curated: true,
    date_created: "2014-11-03T12:55:56",
    date_last_updated: "2024-06-24T03:11:15",
    default_frequency: 2,
    default_image: {
      image: "img/34849_erin_m_b266b4b2-78a1-4a36-811b-94ccc5d07290.png",
      thumbnail: "thmb/34849_erin_m_b266b4b2-78a1-4a36-811b-94ccc5d07290.png",
    },
    default_package_amount: null,
    default_package_units: 0,
    default_units: 1,
    deleted: false,
    description: "",
    directions: [
      {
        id: 257378,
        is_heading: false,
        order: 0,
        recipe: "/api/v1/recipe/34849/",
        resource_uri: "/api/v1/directions/257378/",
        text: "Preheat oven to 375 degrees.  Place chicken in glass baking dish. ",
      },
      {
        id: 257379,
        is_heading: false,
        order: 1,
        recipe: "/api/v1/recipe/34849/",
        resource_uri: "/api/v1/directions/257379/",
        text: "Drizzle olive oil lightly over each breast.  Add generous pinch of rosemary, and small pinch of oregano to each breast. ",
      },
      {
        id: 257380,
        is_heading: false,
        order: 2,
        recipe: "/api/v1/recipe/34849/",
        resource_uri: "/api/v1/directions/257380/",
        text: "Bake uncovered in oven for 45 minutes, until chicken is golden brown and the juices run clear.  ",
      },
    ],
    discrete_units: 0,
    expiration_time: 4,
    extra_info_id: 1368,
    extra_tags: "",
    fats: 26.44334,
    fiber: 2.2077,
    food_group: null,
    food_group_id: null,
    food_name: "Simple Rosemary Chicken Breast",
    food_rating: null,
    fruit_servings: 0,
    icon_thumbnail: "images/food_icons_v3/kebab.png",
    icon_thumbnail_svg: "images/food_icons_v3/kebab.svg",
    id: 34849,
    images: [
      {
        curated: true,
        food_id: 34849,
        id: 4548,
        image: "img/34849_erin_m_b266b4b2-78a1-4a36-811b-94ccc5d07290.png",
        is_primary_image: true,
        source: null,
        thumbnail: "thmb/34849_erin_m_b266b4b2-78a1-4a36-811b-94ccc5d07290.png",
        uploader: "elm333",
      },
      {
        curated: true,
        food_id: 34849,
        id: 11268,
        image: "img/34849_JoelBrewer_a5e55bed-5856-454f-ac49-b840684e919c.png",
        is_primary_image: false,
        source: null,
        thumbnail:
          "thmb/34849_JoelBrewer_a5e55bed-5856-454f-ac49-b840684e919c.png",
        uploader: "JoelBrewer",
      },
      {
        curated: true,
        food_id: 34849,
        id: 66110,
        image: "img/34849_simmyras_bce1fe03-e04f-4ce5-a9ce-9e6fa62abda8.png",
        is_primary_image: false,
        source: null,
        thumbnail:
          "thmb/34849_simmyras_bce1fe03-e04f-4ce5-a9ce-9e6fa62abda8.png",
        uploader: "simmyras",
      },
    ],
    info_id: 1472,
    ingredients: [
      {
        amount: 4,
        food: {
          accurate_grams: true,
          allow_public: true,
          average_frequency: 0,
          blatantly_unhealthy: false,
          breakfast: null,
          calories: 141.6,
          can_be_bulk: null,
          carbs: 0,
          category_id: null,
          cholesterol: 86.14,
          complexity: 1,
          cook_time: 0,
          curated: true,
          date_created: "2014-11-03T12:49:39",
          date_last_updated: "2024-06-27T17:07:23",
          default_frequency: 0,
          default_image: {
            image: "img/451_erin_m_d7cfcfcd-642a-4d6b-b6e8-0adf3eabbff7.png",
            thumbnail:
              "thmb/451_erin_m_d7cfcfcd-642a-4d6b-b6e8-0adf3eabbff7.png",
          },
          default_package_amount: 1,
          default_package_units: 2,
          default_units: 3,
          deleted: false,
          description: "Broilers or fryers, meat only, raw",
          discrete_units: 2,
          expiration_time: 14,
          extra_info_id: 451,
          extra_tags: null,
          fats: 3.0916,
          fiber: 0,
          food_group: 500,
          food_group_id: 500,
          food_name: "Chicken breast",
          food_rating: null,
          fruit_servings: 0,
          icon_thumbnail: "images/food_icons_v3/chicken.png",
          icon_thumbnail_svg: "images/food_icons_v3/chicken.svg",
          id: 451,
          images: [
            {
              curated: true,
              food_id: 451,
              id: 5477,
              image: "img/451_erin_m_d7cfcfcd-642a-4d6b-b6e8-0adf3eabbff7.png",
              is_primary_image: true,
              source: null,
              thumbnail:
                "thmb/451_erin_m_d7cfcfcd-642a-4d6b-b6e8-0adf3eabbff7.png",
              uploader: "elm333",
            },
          ],
          info_id: 492,
          is_basic_food: true,
          is_breakfast: false,
          is_dessert: false,
          is_dinner: false,
          is_discrete: false,
          is_lunch: false,
          is_recipe: false,
          is_seo_primary: true,
          is_snack: false,
          keeps_well: null,
          main_dish: false,
          major_ingredients: "poultry",
          manufactured_by: null,
          mapped_meal_tags:
            "0000000000000000000000000000000000000000000000000000000000000000",
          max_servings: 3,
          meal_tags: 0,
          meta_tags: null,
          min_servings: 0,
          minimum_discrete_amount: 1,
          missing_prices: null,
          model: "u",
          needs_blender: null,
          needs_food_processor: null,
          needs_grill: null,
          needs_microwave: null,
          needs_oven: null,
          needs_slow_cooker: null,
          needs_stove: null,
          needs_toaster: null,
          net_carbs: 0,
          num_favorites: 8696,
          num_frequency_adjustments: 0,
          num_ingredient_usages: 29877,
          num_normalized_ingredient_usages: 40578,
          num_ratings: 0,
          num_reviews: 0,
          number_of_ingredients: 0,
          number_servings: 1,
          nutrition: {
            ala_fatty_acid: 0.013,
            alanine: 1.313,
            alcohol: 0,
            alpha_carotene: 0,
            arginine: 1.521,
            aspartic_acid: 2.116,
            beta_carotene: 0,
            betaine: 7,
            caffeine: 0,
            calcium: 5,
            calories: 120,
            carbs: 0,
            cholesterol: 73,
            choline: 82.1,
            copper: 0.037,
            cystine: 0.236,
            dha_fatty_acid: 0.004,
            dpa_fatty_acid: 0.006,
            epa_fatty_acid: 0.003,
            fats: 2.62,
            fiber: 0,
            fluoride: null,
            folate: 9,
            food_group: 500,
            food_group_id: 500,
            fructose: null,
            fruit_servings: 0,
            galactose: null,
            glucose: null,
            glutamic_acid: 3.333,
            glycine: 0.996,
            histidine: 0.839,
            hydroxyproline: null,
            iron: 0.37,
            isoleucine: 1.104,
            lactose: null,
            leucine: 1.861,
            lycopene: 0,
            lysine: 2.163,
            magnesium: 28,
            maltose: null,
            manganese: 0.011,
            methionine: 0.585,
            monounsaturated_fats: 0.689,
            niacin: 9.6,
            pantothenic_acid: 1.495,
            phenylalanine: 0.908,
            phosphorus: 213,
            polyunsaturated_fats: 0.424,
            potassium: 334,
            price: 0.4434,
            proline: 0.715,
            proteins: 22.5,
            retinol: 7,
            riboflavin: 0.177,
            saturated_fats: 0.563,
            selenium: 22.8,
            serine: 0.858,
            sodium: 45,
            starch: null,
            sucrose: null,
            sugar: 0,
            theobromine: 0,
            thiamine: 0.094,
            threonine: 1.009,
            total_omega_3: 0.026,
            total_omega_6: 0.335,
            trans_fats: 0.007,
            tryptophan: 0.283,
            tyrosine: 0.81,
            valine: 1.165,
            veggie_servings: 0,
            vit_a: 7,
            vit_a_iu: 25,
            vit_b12: 0.21,
            vit_b6: 0.811,
            vit_c: 0,
            vit_d: 0,
            vit_d2: null,
            vit_d3: 0,
            vit_d_iu: 1,
            vit_e: 0.56,
            vit_k: 0.2,
            water: 73.9,
            zinc: 0.68,
          },
          one_time_edit: false,
          perishable: false,
          placeholder_image: "images/recipe_image_placeholder.jpg",
          prep_day_before: false,
          prep_time: 0,
          price: 0.523212,
          proteins: 26.55,
          public_url: "/food/nutrition/chicken-breast,451/",
          resource_uri: "/api/v1/food/451/",
          saturated_fats: 0.66434,
          score: 0,
          serving_calories: 141.6,
          serving_carbs: 0,
          serving_fats: 3.09,
          serving_price: 0.52,
          serving_proteins: 26.55,
          side_dish: null,
          single_serving: true,
          slug: "chicken-breast,451",
          sodium: 53.1,
          source: "UsdaFood",
          substitution_tags: null,
          sugar: 0,
          tag_cloud: "realchicken",
          total_ingredient_usages: 70455,
          total_time: 0,
          trans_fats: 0.00826,
          user_id: null,
          veggie_servings: 0,
          wait_time: 0,
          weights: [
            {
              amount: 100,
              description: "grams",
              grams: 100,
            },
            {
              amount: 1,
              description: "unit (yield from 1 lb ready-to-cook chicken)",
              grams: 71,
            },
            {
              amount: 0.5,
              description: "full breast (both fillets)",
              grams: 118,
            },
            {
              amount: 1,
              description: "breast fillet",
              grams: 118,
            },
            {
              amount: 1,
              description: "oz",
              grams: 28.35,
            },
            {
              amount: 1,
              description: "lb",
              grams: 453.6,
            },
          ],
        },
        id: 742356,
        order: 0,
        preparation: null,
        recipe: "/api/v1/recipe/34849/",
        resource_uri: "/api/v1/ingredients/742356/",
        scaled_amount: 4,
        units: 2,
      },
      {
        amount: 1,
        food: {
          accurate_grams: true,
          allow_public: true,
          average_frequency: 0,
          blatantly_unhealthy: false,
          breakfast: null,
          calories: 10.923,
          can_be_bulk: null,
          carbs: 2.11398,
          category_id: null,
          cholesterol: 0,
          complexity: 1,
          cook_time: 0,
          curated: true,
          date_created: "2014-11-03T12:49:38",
          date_last_updated: "2024-06-24T07:35:19",
          default_frequency: 0,
          default_image: {
            image: "img/211_erin_m_9dbb9005-f653-4007-957a-8a372cc82121.png",
            thumbnail:
              "thmb/211_erin_m_9dbb9005-f653-4007-957a-8a372cc82121.png",
          },
          default_package_amount: 2,
          default_package_units: 1,
          default_units: 1,
          deleted: false,
          description: "Spices, dried",
          discrete_units: 1,
          expiration_time: 14,
          extra_info_id: 211,
          extra_tags: null,
          fats: 0.50226,
          fiber: 1.4058,
          food_group: 200,
          food_group_id: 200,
          food_name: "Rosemary",
          food_rating: null,
          fruit_servings: 0,
          icon_thumbnail: "images/food_icons_v3/pepper_shaker.png",
          icon_thumbnail_svg: "images/food_icons_v3/pepper_shaker.svg",
          id: 211,
          images: [
            {
              curated: true,
              food_id: 211,
              id: 5770,
              image: "img/211_erin_m_9dbb9005-f653-4007-957a-8a372cc82121.png",
              is_primary_image: true,
              source: null,
              thumbnail:
                "thmb/211_erin_m_9dbb9005-f653-4007-957a-8a372cc82121.png",
              uploader: "elm333",
            },
          ],
          info_id: 238,
          is_basic_food: true,
          is_breakfast: false,
          is_dessert: false,
          is_dinner: false,
          is_discrete: false,
          is_lunch: false,
          is_recipe: false,
          is_seo_primary: true,
          is_snack: false,
          keeps_well: null,
          main_dish: false,
          major_ingredients: "rosemary",
          manufactured_by: null,
          mapped_meal_tags:
            "0000000000000000000000000000000000000000000000000000000000000000",
          max_servings: 3,
          meal_tags: 0,
          meta_tags: null,
          min_servings: 0,
          minimum_discrete_amount: 1,
          missing_prices: null,
          model: "u",
          needs_blender: null,
          needs_food_processor: null,
          needs_grill: null,
          needs_microwave: null,
          needs_oven: null,
          needs_slow_cooker: null,
          needs_stove: null,
          needs_toaster: null,
          net_carbs: 0.70818,
          num_favorites: 373,
          num_frequency_adjustments: 0,
          num_ingredient_usages: 1451,
          num_normalized_ingredient_usages: 3589,
          num_ratings: 0,
          num_reviews: 0,
          number_of_ingredients: 0,
          number_servings: 1,
          nutrition: {
            ala_fatty_acid: null,
            alanine: null,
            alcohol: 0,
            alpha_carotene: null,
            arginine: null,
            aspartic_acid: null,
            beta_carotene: null,
            betaine: null,
            caffeine: null,
            calcium: 1280,
            calories: 331,
            carbs: 64.06,
            cholesterol: 0,
            choline: null,
            copper: 0.55,
            cystine: null,
            dha_fatty_acid: 0,
            dpa_fatty_acid: 0,
            epa_fatty_acid: 0,
            fats: 15.22,
            fiber: 42.6,
            fluoride: null,
            folate: 307,
            food_group: 200,
            food_group_id: 200,
            fructose: null,
            fruit_servings: 0,
            galactose: null,
            glucose: null,
            glutamic_acid: null,
            glycine: null,
            histidine: null,
            hydroxyproline: null,
            iron: 29.25,
            isoleucine: null,
            lactose: null,
            leucine: null,
            lycopene: null,
            lysine: null,
            magnesium: 220,
            maltose: null,
            manganese: 1.867,
            methionine: null,
            monounsaturated_fats: 3.014,
            niacin: 1,
            pantothenic_acid: null,
            phenylalanine: null,
            phosphorus: 70,
            polyunsaturated_fats: 2.339,
            potassium: 955,
            price: 0.83,
            proline: null,
            proteins: 4.88,
            retinol: 0,
            riboflavin: 0.428,
            saturated_fats: 7.371,
            selenium: 4.6,
            serine: null,
            sodium: 50,
            starch: null,
            sucrose: null,
            sugar: null,
            theobromine: null,
            thiamine: 0.514,
            threonine: null,
            total_omega_3: 0,
            total_omega_6: 0,
            trans_fats: null,
            tryptophan: null,
            tyrosine: null,
            valine: null,
            veggie_servings: 0,
            vit_a: 156,
            vit_a_iu: 3128,
            vit_b12: 0,
            vit_b6: 1.74,
            vit_c: 61.2,
            vit_d: 0,
            vit_d2: null,
            vit_d3: null,
            vit_d_iu: 0,
            vit_e: null,
            vit_k: null,
            water: 9.31,
            zinc: 3.23,
          },
          one_time_edit: false,
          perishable: false,
          placeholder_image: "images/recipe_image_placeholder.jpg",
          prep_day_before: false,
          prep_time: 0,
          price: 0.02739,
          proteins: 0.16104,
          public_url: "/food/nutrition/rosemary,211/",
          resource_uri: "/api/v1/food/211/",
          saturated_fats: 0.243243,
          score: 0,
          serving_calories: 10.92,
          serving_carbs: 2.11,
          serving_fats: 0.5,
          serving_price: 0.03,
          serving_proteins: 0.16,
          side_dish: null,
          single_serving: true,
          slug: "rosemary,211",
          sodium: 1.65,
          source: "UsdaFood",
          substitution_tags: null,
          sugar: null,
          tag_cloud: null,
          total_ingredient_usages: 5040,
          total_time: 0,
          trans_fats: null,
          user_id: null,
          veggie_servings: 0,
          wait_time: 0,
          weights: [
            {
              amount: 100,
              description: "grams",
              grams: 100,
            },
            {
              amount: 1,
              description: "tbsp",
              grams: 3.3,
            },
            {
              amount: 1,
              description: "tsp",
              grams: 1.2,
            },
            {
              amount: 1,
              description: "cup",
              grams: 52.8,
            },
          ],
        },
        id: 742357,
        order: 1,
        preparation: null,
        recipe: "/api/v1/recipe/34849/",
        resource_uri: "/api/v1/ingredients/742357/",
        scaled_amount: 1,
        units: 1,
      },
      {
        amount: 1,
        food: {
          accurate_grams: true,
          allow_public: true,
          average_frequency: 0,
          blatantly_unhealthy: false,
          breakfast: null,
          calories: 7.95,
          can_be_bulk: null,
          carbs: 2.0676,
          category_id: null,
          cholesterol: 0,
          complexity: 1,
          cook_time: 0,
          curated: true,
          date_created: "2014-11-03T12:49:38",
          date_last_updated: "2024-06-27T17:10:00",
          default_frequency: 0,
          default_image: {
            image: "img/202_erin_m_c761765a-65bd-4792-b231-4be25f3eebde.png",
            thumbnail:
              "thmb/202_erin_m_c761765a-65bd-4792-b231-4be25f3eebde.png",
          },
          default_package_amount: 2,
          default_package_units: 3,
          default_units: 3,
          deleted: false,
          description: "Spices, dried",
          discrete_units: 3,
          expiration_time: 14,
          extra_info_id: 202,
          extra_tags: null,
          fats: 0.1284,
          fiber: 1.275,
          food_group: 200,
          food_group_id: 200,
          food_name: "Oregano",
          food_rating: null,
          fruit_servings: 0,
          icon_thumbnail: "images/food_icons_v3/pepper_shaker.png",
          icon_thumbnail_svg: "images/food_icons_v3/pepper_shaker.svg",
          id: 202,
          images: [
            {
              curated: true,
              food_id: 202,
              id: 5508,
              image: "img/202_erin_m_c761765a-65bd-4792-b231-4be25f3eebde.png",
              is_primary_image: true,
              source: null,
              thumbnail:
                "thmb/202_erin_m_c761765a-65bd-4792-b231-4be25f3eebde.png",
              uploader: "elm333",
            },
          ],
          info_id: 229,
          is_basic_food: true,
          is_breakfast: false,
          is_dessert: false,
          is_dinner: false,
          is_discrete: false,
          is_lunch: false,
          is_recipe: false,
          is_seo_primary: true,
          is_snack: false,
          keeps_well: null,
          main_dish: false,
          major_ingredients: "oregano",
          manufactured_by: null,
          mapped_meal_tags:
            "0000000000000000000000000000000000000000000000000000000000000000",
          max_servings: 3,
          meal_tags: 0,
          meta_tags: null,
          min_servings: 0,
          minimum_discrete_amount: 1,
          missing_prices: null,
          model: "u",
          needs_blender: null,
          needs_food_processor: null,
          needs_grill: null,
          needs_microwave: null,
          needs_oven: null,
          needs_slow_cooker: null,
          needs_stove: null,
          needs_toaster: null,
          net_carbs: 0.7926,
          num_favorites: 1029,
          num_frequency_adjustments: 0,
          num_ingredient_usages: 8421,
          num_normalized_ingredient_usages: 8423,
          num_ratings: 0,
          num_reviews: 0,
          number_of_ingredients: 0,
          number_servings: 1,
          nutrition: {
            ala_fatty_acid: 0.621,
            alanine: 0.5,
            alcohol: 0,
            alpha_carotene: 20,
            arginine: 0.449,
            aspartic_acid: 1.009,
            beta_carotene: 1007,
            betaine: 9.8,
            caffeine: 0,
            calcium: 1597,
            calories: 265,
            carbs: 68.92,
            cholesterol: 0,
            choline: 32.3,
            copper: 0.633,
            cystine: 0.11,
            dha_fatty_acid: 0,
            dpa_fatty_acid: 0,
            epa_fatty_acid: 0,
            fats: 4.28,
            fiber: 42.5,
            fluoride: null,
            folate: 237,
            food_group: 200,
            food_group_id: 200,
            fructose: 1.13,
            fruit_servings: 0,
            galactose: 0.15,
            glucose: 1.9,
            glutamic_acid: 0.975,
            glycine: 0.517,
            histidine: 0.144,
            hydroxyproline: 0,
            iron: 36.8,
            isoleucine: 0.441,
            lactose: 0,
            leucine: 0.78,
            lycopene: 0,
            lysine: 0.5,
            magnesium: 270,
            maltose: 0,
            manganese: 4.99,
            methionine: 0.127,
            monounsaturated_fats: 0.716,
            niacin: 4.64,
            pantothenic_acid: 0.921,
            phenylalanine: 0.449,
            phosphorus: 148,
            polyunsaturated_fats: 1.369,
            potassium: 1260,
            price: 0.88235,
            proline: 1.712,
            proteins: 9,
            retinol: 0,
            riboflavin: 0.528,
            saturated_fats: 1.551,
            selenium: 4.5,
            serine: 0.314,
            sodium: 25,
            starch: null,
            sucrose: 0.91,
            sugar: 4.09,
            theobromine: 0,
            thiamine: 0.177,
            threonine: 0.322,
            total_omega_3: 0.621,
            total_omega_6: 0,
            trans_fats: 0,
            tryptophan: 0.203,
            tyrosine: 0.297,
            valine: 0.585,
            veggie_servings: 0,
            vit_a: 85,
            vit_a_iu: 1701,
            vit_b12: 0,
            vit_b6: 1.044,
            vit_c: 2.3,
            vit_d: 0,
            vit_d2: null,
            vit_d3: null,
            vit_d_iu: 0,
            vit_e: 18.26,
            vit_k: 621.7,
            water: 9.93,
            zinc: 2.69,
          },
          one_time_edit: false,
          perishable: false,
          placeholder_image: "images/recipe_image_placeholder.jpg",
          prep_day_before: false,
          prep_time: 0,
          price: 0.0264705,
          proteins: 0.27,
          public_url: "/food/nutrition/oregano,202/",
          resource_uri: "/api/v1/food/202/",
          saturated_fats: 0.04653,
          score: 0,
          serving_calories: 4.77,
          serving_carbs: 1.24,
          serving_fats: 0.08,
          serving_price: 0.02,
          serving_proteins: 0.16,
          side_dish: null,
          single_serving: true,
          slug: "oregano,202",
          sodium: 0.75,
          source: "UsdaFood",
          substitution_tags: null,
          sugar: 0.1227,
          tag_cloud: null,
          total_ingredient_usages: 16844,
          total_time: 0,
          trans_fats: 0,
          user_id: null,
          veggie_servings: 0,
          wait_time: 0,
          weights: [
            {
              amount: 100,
              description: "grams",
              grams: 100,
            },
            {
              amount: 1,
              description: "tsp, leaves",
              grams: 1,
            },
            {
              amount: 1,
              description: "tsp, ground",
              grams: 1.8,
            },
            {
              amount: 1,
              description: "tbsp, leaves",
              grams: 3,
            },
            {
              amount: 1,
              description: "tbsp, ground",
              grams: 6,
            },
          ],
        },
        id: 742358,
        order: 2,
        preparation: null,
        recipe: "/api/v1/recipe/34849/",
        resource_uri: "/api/v1/ingredients/742358/",
        scaled_amount: 0.6,
        units: 2,
      },
      {
        amount: 1,
        food: {
          accurate_grams: true,
          allow_public: true,
          average_frequency: 0,
          blatantly_unhealthy: false,
          breakfast: null,
          calories: 119.34,
          can_be_bulk: null,
          carbs: 0,
          category_id: null,
          cholesterol: 0,
          complexity: 1,
          cook_time: 0,
          curated: true,
          date_created: "2014-11-03T12:49:38",
          date_last_updated: "2024-06-20T23:02:21",
          default_frequency: 0,
          default_image: {
            image: "img/266_erin_m_4ba6ff1c-ff73-4e96-a5b3-b844d24d3719.png",
            thumbnail:
              "thmb/266_erin_m_4ba6ff1c-ff73-4e96-a5b3-b844d24d3719.png",
          },
          default_package_amount: 16,
          default_package_units: 1,
          default_units: 1,
          deleted: false,
          description: "Salad or cooking",
          discrete_units: 1,
          expiration_time: 14,
          extra_info_id: 266,
          extra_tags: null,
          fats: 13.5,
          fiber: 0,
          food_group: 400,
          food_group_id: 400,
          food_name: "Olive oil",
          food_rating: null,
          fruit_servings: 0,
          icon_thumbnail: "images/food_icons_v3/bottle.png",
          icon_thumbnail_svg: "images/food_icons_v3/bottle.svg",
          id: 266,
          images: [
            {
              curated: true,
              food_id: 266,
              id: 5714,
              image: "img/266_erin_m_4ba6ff1c-ff73-4e96-a5b3-b844d24d3719.png",
              is_primary_image: true,
              source: null,
              thumbnail:
                "thmb/266_erin_m_4ba6ff1c-ff73-4e96-a5b3-b844d24d3719.png",
              uploader: "elm333",
            },
          ],
          info_id: 298,
          is_basic_food: true,
          is_breakfast: false,
          is_dessert: false,
          is_dinner: false,
          is_discrete: false,
          is_lunch: false,
          is_recipe: false,
          is_seo_primary: true,
          is_snack: false,
          keeps_well: null,
          main_dish: false,
          major_ingredients: "olive-oil",
          manufactured_by: null,
          mapped_meal_tags:
            "0000000000000000000000000000000000000000000000000000000000000000",
          max_servings: 3,
          meal_tags: 0,
          meta_tags: null,
          min_servings: 0,
          minimum_discrete_amount: 1,
          missing_prices: null,
          model: "u",
          needs_blender: null,
          needs_food_processor: null,
          needs_grill: null,
          needs_microwave: null,
          needs_oven: null,
          needs_slow_cooker: null,
          needs_stove: null,
          needs_toaster: null,
          net_carbs: 0,
          num_favorites: 6331,
          num_frequency_adjustments: 0,
          num_ingredient_usages: 71589,
          num_normalized_ingredient_usages: 71603,
          num_ratings: 0,
          num_reviews: 0,
          number_of_ingredients: 0,
          number_servings: 1,
          nutrition: {
            ala_fatty_acid: null,
            alanine: 0,
            alcohol: 0,
            alpha_carotene: 0,
            arginine: 0,
            aspartic_acid: 0,
            beta_carotene: 0,
            betaine: 0.1,
            caffeine: 0,
            calcium: 1,
            calories: 884,
            carbs: 0,
            cholesterol: 0,
            choline: 0.3,
            copper: 0,
            cystine: 0,
            dha_fatty_acid: 0,
            dpa_fatty_acid: 0,
            epa_fatty_acid: 0,
            fats: 100,
            fiber: 0,
            fluoride: null,
            folate: 0,
            food_group: 400,
            food_group_id: 400,
            fructose: null,
            fruit_servings: 0,
            galactose: null,
            glucose: null,
            glutamic_acid: 0,
            glycine: 0,
            histidine: 0,
            hydroxyproline: null,
            iron: 0.56,
            isoleucine: 0,
            lactose: null,
            leucine: 0,
            lycopene: 0,
            lysine: 0,
            magnesium: 0,
            maltose: null,
            manganese: 0,
            methionine: 0,
            monounsaturated_fats: 72.961,
            niacin: 0,
            pantothenic_acid: 0,
            phenylalanine: 0,
            phosphorus: 0,
            polyunsaturated_fats: 10.523,
            potassium: 1,
            price: 1.55,
            proline: 0,
            proteins: 0,
            retinol: 0,
            riboflavin: 0,
            saturated_fats: 13.808,
            selenium: 0,
            serine: 0,
            sodium: 2,
            starch: null,
            sucrose: null,
            sugar: 0,
            theobromine: 0,
            thiamine: 0,
            threonine: 0,
            total_omega_3: 0,
            total_omega_6: 0,
            trans_fats: null,
            tryptophan: 0,
            tyrosine: 0,
            valine: 0,
            veggie_servings: 0,
            vit_a: 0,
            vit_a_iu: 0,
            vit_b12: 0,
            vit_b6: 0,
            vit_c: 0,
            vit_d: 0,
            vit_d2: null,
            vit_d3: null,
            vit_d_iu: 0,
            vit_e: 14.35,
            vit_k: 60.2,
            water: 0,
            zinc: 0,
          },
          one_time_edit: false,
          perishable: false,
          placeholder_image: "images/recipe_image_placeholder.jpg",
          prep_day_before: false,
          prep_time: 0,
          price: 0.20925,
          proteins: 0,
          public_url: "/food/nutrition/olive-oil,266/",
          resource_uri: "/api/v1/food/266/",
          saturated_fats: 1.86408,
          score: 0,
          serving_calories: 119.34,
          serving_carbs: 0,
          serving_fats: 13.5,
          serving_price: 0.21,
          serving_proteins: 0,
          side_dish: null,
          single_serving: true,
          slug: "olive-oil,266",
          sodium: 0.27,
          source: "UsdaFood",
          substitution_tags: null,
          sugar: 0,
          tag_cloud: null,
          total_ingredient_usages: 143192,
          total_time: 0,
          trans_fats: null,
          user_id: null,
          veggie_servings: 0,
          wait_time: 0,
          weights: [
            {
              amount: 100,
              description: "grams",
              grams: 100,
            },
            {
              amount: 1,
              description: "tbsp",
              grams: 13.5,
            },
            {
              amount: 1,
              description: "cup",
              grams: 216,
            },
            {
              amount: 1,
              description: "tsp",
              grams: 4.5,
            },
          ],
        },
        id: 742359,
        order: 3,
        preparation: null,
        recipe: "/api/v1/recipe/34849/",
        resource_uri: "/api/v1/ingredients/742359/",
        scaled_amount: 1,
        units: 1,
      },
    ],
    is_basic_food: false,
    is_breakfast: false,
    is_dessert: false,
    is_dinner: true,
    is_discrete: false,
    is_lunch: true,
    is_recipe: true,
    is_seo_primary: false,
    is_snack: false,
    keeps_well: true,
    main_dish: true,
    major_ingredients: "poultry simple-rosemary-chicken-breast",
    manufactured_by: null,
    mapped_meal_tags:
      "0000000010000010000000110000000000100000000000000000000000000000",
    max_servings: 3,
    meal_tags: 17192468736,
    meta_tags: "",
    min_servings: 0,
    minimum_discrete_amount: 0,
    missing_prices: null,
    model: "r",
    needs_blender: false,
    needs_food_processor: false,
    needs_grill: false,
    needs_microwave: false,
    needs_oven: true,
    needs_slow_cooker: false,
    needs_stove: false,
    needs_toaster: false,
    net_carbs: 1.12838,
    num_favorites: 1434,
    num_frequency_adjustments: 0,
    num_ingredient_usages: 0,
    num_normalized_ingredient_usages: 0,
    num_ratings: 36976,
    num_reviews: 0,
    number_of_ingredients: 4,
    number_servings: 2,
    nutrition: {
      ala_fatty_acid: 0.01,
      alanine: 1.26,
      alcohol: 0,
      alpha_carotene: 0.07,
      arginine: 1.46,
      aspartic_acid: 2.04,
      beta_carotene: 3.69,
      betaine: 6.77,
      caffeine: 0,
      calcium: 19.31,
      calories: 142.98,
      carbs: 0.68,
      cholesterol: 70.23,
      choline: 79.12,
      copper: 0.04,
      cystine: 0.23,
      dha_fatty_acid: 0,
      dpa_fatty_acid: 0.01,
      epa_fatty_acid: 0,
      fats: 5.39,
      fiber: 0.45,
      fluoride: 0,
      folate: 11.6,
      fructose: 0,
      fruit_servings: 0,
      galactose: 0,
      glucose: 0.01,
      glutamic_acid: 3.21,
      glycine: 0.96,
      histidine: 0.81,
      hydroxyproline: 0,
      iron: 0.72,
      isoleucine: 1.06,
      lactose: 0,
      leucine: 1.79,
      lycopene: 0,
      lysine: 2.08,
      magnesium: 29.41,
      maltose: 0,
      manganese: 0.04,
      methionine: 0.56,
      monounsaturated_fats: 2.69,
      niacin: 9.27,
      pantothenic_acid: 1.44,
      phenylalanine: 0.87,
      phosphorus: 205.93,
      polyunsaturated_fats: 0.73,
      potassium: 332.41,
      price: 0.48,
      proline: 0.7,
      proteins: 21.71,
      retinol: 6.73,
      riboflavin: 0.17,
      saturated_fats: 0.98,
      selenium: 21.99,
      serine: 0.83,
      sodium: 43.78,
      starch: 0,
      sucrose: 0,
      sugar: 0.02,
      theobromine: 0,
      thiamine: 0.09,
      threonine: 0.97,
      total_omega_3: 0.03,
      total_omega_6: 0.32,
      trans_fats: 0.01,
      tryptophan: 0.27,
      tyrosine: 0.78,
      valine: 1.12,
      veggie_servings: 0,
      vit_a: 8.09,
      vit_a_iu: 51.33,
      vit_b12: 0.2,
      vit_b6: 0.79,
      vit_c: 0.42,
      vit_d: 0,
      vit_d2: 0,
      vit_d3: 0,
      vit_d_iu: 0.96,
      vit_e: 1,
      vit_k: 4.13,
      water: 71.2,
      zinc: 0.68,
    },
    one_time_edit: false,
    perishable: false,
    placeholder_image: "images/recipe_image_placeholder.jpg",
    prep_day_before: false,
    prep_time: 5,
    price: 2.35488,
    proteins: 106.50926,
    public_url: "/recipe/nutrition/simple-rosemary-chicken-breast,34849/",
    resource_uri: "/api/v1/recipe/34849/",
    saturated_fats: 4.80788,
    score: 0.886615699873479,
    serving_calories: 350.73,
    serving_carbs: 1.67,
    serving_fats: 13.22,
    serving_price: 1.18,
    serving_proteins: 53.25,
    side_dish: false,
    single_serving: true,
    slug: "simple-rosemary-chicken-breast,34849",
    sodium: 214.78468,
    source: "Recipe",
    substitution_tags: "",
    sugar: 0.09812,
    tag_cloud:
      'Chicken breast Poultry Products realchicken Rosemary Spices and Herbs Oregano Olive oil Fats and Oils "Simple Rosemary Chicken Breast" ',
    total_ingredient_usages: 0,
    total_time: 50,
    trans_fats: 0.04906,
    uploader: "HurricaneJen",
    user_id: 7691,
    veggie_servings: 0,
    wait_time: 0,
    weights: [
      {
        amount: 100,
        description: "grams",
        grams: 100,
      },
      {
        amount: 1,
        description: "breast",
        grams: 245.3,
      },
    ],
  };

  const recipe = await Recipe.findByIdAndUpdate("6662bfbdf1f800fd7aab2489", x);
};
//    ingredients: [
//       {
//         amount: {
//           type: "Number",
//         },
//         food: {
//           accurate_grams: {
//             type: "Boolean",
//           },

//           average_frequency: {
//             type: "Number",
//           },
//           blatantly_unhealthy: {
//             type: "Boolean",
//           },
//           breakfast: {
//             type: "Mixed",
//           },
//           calories: {
//             type: "Number",
//           },
//           can_be_bulk: {
//             type: "Mixed",
//           },
//           carbs: {
//             type: "Number",
//           },
//           category_id: {
//             type: "Mixed",
//           },
//           cholesterol: {
//             type: "Number",
//           },
//           complexity: {
//             type: "Number",
//           },
//           cook_time: {
//             type: "Number",
//           },
//           curated: {
//             type: "Boolean",
//           },
//           date_created: {
//             type: "Date",
//           },
//           date_last_updated: {
//             type: "Date",
//           },
//           default_frequency: {
//             type: "Number",
//           },
//           default_image: {
//             image: {
//               type: "String",
//             },
//             thumbnail: {
//               type: "String",
//             },
//           },

//           description: {
//             type: "String",
//           },
//           discrete_units: {
//             type: "Number",
//           },
//           expiration_time: {
//             type: "Number",
//           },
//           extra_info_id: {
//             type: "Number",
//           },
//           extra_tags: {
//             type: "Mixed",
//           },
//           fats: {
//             type: "Number",
//           },
//           fiber: {
//             type: "Number",
//           },
//           food_group: {
//             type: "Number",
//           },
//           food_group_id: {
//             type: "Number",
//           },
//           food_name: {
//             type: "String",
//           },
//           food_rating: {
//             type: "Mixed",
//           },
//           fruit_servings: {
//             type: "Number",
//           },
//           icon_thumbnail: {
//             type: "String",
//           },
//           icon_thumbnail_svg: {
//             type: "String",
//           },
//           id: {
//             type: "Number",
//           },
//           images: {
//             type: ["Mixed"],
//           },
//           info_id: {
//             type: "Number",
//           },
//           is_basic_food: {
//             type: "Boolean",
//           },
//           is_breakfast: {
//             type: "Boolean",
//           },
//           is_dessert: {
//             type: "Boolean",
//           },
//           is_dinner: {
//             type: "Boolean",
//           },
//           is_discrete: {
//             type: "Boolean",
//           },
//           is_lunch: {
//             type: "Boolean",
//           },
//           is_recipe: {
//             type: "Boolean",
//           },
//           is_seo_primary: {
//             type: "Boolean",
//           },
//           is_snack: {
//             type: "Boolean",
//           },
//           keeps_well: {
//             type: "Mixed",
//           },
//           main_dish: {
//             type: "Boolean",
//           },
//           major_ingredients: {
//             type: "String",
//           },
//           manufactured_by: {
//             type: "Mixed",
//           },
//           mapped_meal_tags: {
//             type: "Date",
//           },
//           max_servings: {
//             type: "Number",
//           },
//           meal_tags: {
//             type: "Number",
//           },
//           meta_tags: {
//             type: "Mixed",
//           },
//           min_servings: {
//             type: "Number",
//           },
//           minimum_discrete_amount: {
//             type: "Number",
//           },
//           missing_prices: {
//             type: "Mixed",
//           },
//           model: {
//             type: "String",
//           },
//           needs_blender: {
//             type: "Mixed",
//           },
//           needs_food_processor: {
//             type: "Mixed",
//           },
//           needs_grill: {
//             type: "Mixed",
//           },
//           needs_microwave: {
//             type: "Mixed",
//           },
//           needs_oven: {
//             type: "Mixed",
//           },
//           needs_slow_cooker: {
//             type: "Mixed",
//           },
//           needs_stove: {
//             type: "Mixed",
//           },
//           needs_toaster: {
//             type: "Mixed",
//           },
//           net_carbs: {
//             type: "Number",
//           },
//           num_favorites: {
//             type: "Number",
//           },
//           num_frequency_adjustments: {
//             type: "Number",
//           },
//           num_ingredient_usages: {
//             type: "Number",
//           },
//           num_normalized_ingredient_usages: {
//             type: "Number",
//           },
//           num_ratings: {
//             type: "Number",
//           },
//           num_reviews: {
//             type: "Number",
//           },
//           number_of_ingredients: {
//             type: "Number",
//           },
//           number_servings: {
//             type: "Number",
//           },
//           nutrition: {},
//           one_time_edit: {
//             type: "Boolean",
//           },
//           perishable: {
//             type: "Boolean",
//           },
//           placeholder_image: {
//             type: "String",
//           },
//           prep_day_before: {
//             type: "Boolean",
//           },
//           prep_time: {
//             type: "Number",
//           },
//           price: {
//             type: "Number",
//           },
//           proteins: {
//             type: "Number",
//           },
//           public_url: {
//             type: "Date",
//           },
//           resource_uri: {
//             type: "String",
//           },
//           saturated_fats: {
//             type: "Number",
//           },
//           score: {
//             type: "Number",
//           },
//           serving_calories: {
//             type: "Number",
//           },
//           serving_carbs: {
//             type: "Number",
//           },
//           serving_fats: {
//             type: "Number",
//           },
//           serving_price: {
//             type: "Number",
//           },
//           serving_proteins: {
//             type: "Number",
//           },
//           side_dish: {
//             type: "Mixed",
//           },
//           single_serving: {
//             type: "Boolean",
//           },
//           slug: {
//             type: "Date",
//           },
//           sodium: {
//             type: "Number",
//           },
//           source: {
//             type: "String",
//           },
//           substitution_tags: {
//             type: "Mixed",
//           },
//           sugar: {
//             type: "Number",
//           },
//           tag_cloud: {
//             type: "Mixed",
//           },
//           total_ingredient_usages: {
//             type: "Number",
//           },
//           total_time: {
//             type: "Number",
//           },
//           trans_fats: {
//             type: "Number",
//           },
//           user_id: {
//             type: "Mixed",
//           },
//           veggie_servings: {
//             type: "Number",
//           },
//           wait_time: {
//             type: "Number",
//           },
//           weights: {
//             type: ["Mixed"],
//           },
//         },
//         order: {
//           type: "Number",
//         },

//         scaled_amount: {
//           type: "Number",
//         },
//         units: {
//           type: "Number",
//         },
//       },
//     ],
