name: Test

on:
    workflow_dispatch: 
    push:
        branches:
            master
jobs:
    hell-world:
        name: 'say hell world'
        runs-on: ubuntu-latest
        steps:
            - name: "echo"
              run: echo hell world